name: "AutoPublish"

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  auto-publish:
    name: "AutoPublish on master"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5"  # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run build
      - name: "Automated Release"
        uses: "phips28/gh-action-bump-version@215e27a882516826c59df7f09da8c67d5f375cbd"  # master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
